apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/dariasmoises979-blip/pipeline-build.git'  # Repo donde est√° el chart
    targetRevision: main                                 # Rama o tag
    path: kubernetes/helm-manifest                    # Ruta al chart dentro del repo
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicaCount
          value: "3"

  destination:
    server: 'https://kubernetes.default.svc'            # Cluster local
    namespace: helloworld                                # Namespace de destino

  syncPolicy:
    automated:
      prune: true          # Elimina recursos no declarados
      selfHeal: true       # Re-aplica cambios si alguien los modifica fuera de ArgoCD
