apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-tls-staging
  namespace: infra
spec:
  secretName: demo-tls-staging-secret
  dnsNames:
    - demo.example.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer