apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: users-vs
  namespace: production
spec:
  hosts:
  - "demo.example.com"
  gateways:
  - istio-system/istio-prod-gateway
  http:
  - match:
    - uri:
        prefix: /users
    route:
    - destination:
        host: users.production.svc.cluster.local
        port:
          number: 80